# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\QT_program\battry_system\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore
from PyQt5 import QtWidgets
from PyQt5.QtGui import QIcon
import SQLb as s
from PyQt5.QtWidgets import QMessageBox


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(469, 380)
        Form.setStyleSheet("background-color: rgb(225, 237, 255);")
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.second = QtWidgets.QWidget(Form)
        self.second.setGeometry(QtCore.QRect(10, 100, 451, 81))
        self.second.setObjectName("second")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.second)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.old = QtWidgets.QLabel(self.second)
        self.old.setStyleSheet("font:15px \"微软雅黑\";")
        self.old.setObjectName("old")
        self.horizontalLayout_4.addWidget(self.old)
        self.n2 = QtWidgets.QLineEdit(self.second)
        self.n2.setMinimumSize(QtCore.QSize(0, 30))
        self.n2.setToolTip("")
        self.n2.setStyleSheet("background:white;\n"
                              "    padding-left:5px ;\n"
                              "    padding-top:1px ;\n"
                              "    border-bottom-left-radius:3px;\n"
                              "    border-bottom-right-radius:3px;\n"
                              "    border: 1px solid rgb(209 , 209 , 209);\n"
                              "    border-top:transparent;")
        self.n2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.n2.setObjectName("n2")
        self.horizontalLayout_4.addWidget(self.n2)
        self.first = QtWidgets.QWidget(Form)
        self.first.setGeometry(QtCore.QRect(10, 10, 451, 81))
        self.first.setObjectName("first")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.first)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.numberr = QtWidgets.QLabel(self.first)
        self.numberr.setStyleSheet("font:15px \"微软雅黑\";")
        self.numberr.setObjectName("numberr")
        self.horizontalLayout_5.addWidget(self.numberr)
        self.n1 = QtWidgets.QLineEdit(self.first)
        self.n1.setMinimumSize(QtCore.QSize(0, 30))
        self.n1.setStyleSheet("background:white;\n"
                              "    padding-left:5px ;\n"
                              "    padding-top:1px ;\n"
                              "    border-bottom-left-radius:3px;\n"
                              "    border-bottom-right-radius:3px;\n"
                              "    border: 1px solid rgb(209 , 209 , 209);\n"
                              "    border-top:transparent;")
        self.n1.setObjectName("n1")
        self.horizontalLayout_5.addWidget(self.n1)
        self.button = QtWidgets.QWidget(Form)
        self.button.setGeometry(QtCore.QRect(10, 280, 451, 91))
        self.button.setObjectName("button")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.button)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.yess = QtWidgets.QPushButton(self.button)
        self.yess.setMinimumSize(QtCore.QSize(150, 50))
        self.yess.setStyleSheet("QPushButton\n"
                                "{\n"
                                "    color:white;\n"
                                "    background-color:rgb(14 , 150 , 254);\n"
                                "    border-radius:5px;\n"
                                "    font:20px \"微软雅黑\";\n"
                                "}\n"
                                "\n"
                                "::hover\n"
                                "{\n"
                                "    color:white;\n"
                                "    background-color:rgb(44 , 137 , 255);\n"
                                "}\n"
                                "\n"
                                "::pressed\n"
                                "{\n"
                                "    color:white;\n"
                                "    background-color:rgb(14 , 135 , 228);\n"
                                "    padding-left:3px;\n"
                                "    padding-top:3px;\n"
                                "}")
        self.yess.setObjectName("yess")
        self.horizontalLayout_6.addWidget(self.yess)
        spacerItem = QtWidgets.QSpacerItem(
            82, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.closee = QtWidgets.QPushButton(self.button)
        self.closee.setMinimumSize(QtCore.QSize(150, 50))
        self.closee.setStyleSheet("QPushButton\n"
                                  "{\n"
                                  "    color:white;\n"
                                  "    background-color:rgb(14 , 150 , 254);\n"
                                  "    border-radius:5px;\n"
                                  "    font:20px \"微软雅黑\";\n"
                                  "}\n"
                                  "\n"
                                  ":hover\n"
                                  "{\n"
                                  "    color:white;\n"
                                  "    background-color:rgb(44 , 137 , 255);\n"
                                  "}\n"
                                  "\n"
                                  ":pressed\n"
                                  "{\n"
                                  "    color:white;\n"
                                  "    background-color:rgb(14 , 135 , 228);\n"
                                  "    padding-left:3px;\n"
                                  "    padding-top:3px;\n"
                                  "}")
        self.closee.setObjectName("closee")
        self.horizontalLayout_6.addWidget(self.closee)
        self.second_2 = QtWidgets.QWidget(Form)
        self.second_2.setGeometry(QtCore.QRect(10, 190, 451, 81))
        self.second_2.setObjectName("second_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.second_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.neww = QtWidgets.QLabel(self.second_2)
        self.neww.setStyleSheet("font:15px \"微软雅黑\";")
        self.neww.setObjectName("neww")
        self.horizontalLayout_7.addWidget(self.neww)
        self.n3 = QtWidgets.QLineEdit(self.second_2)
        self.n3.setMinimumSize(QtCore.QSize(0, 30))
        self.n3.setToolTip("")
        self.n3.setStyleSheet("background:white;\n"
                              "    padding-left:5px ;\n"
                              "    padding-top:1px ;\n"
                              "    border-bottom-left-radius:3px;\n"
                              "    border-bottom-right-radius:3px;\n"
                              "    border: 1px solid rgb(209 , 209 , 209);\n"
                              "    border-top:transparent;")
        self.n3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.n3.setObjectName("n3")
        self.horizontalLayout_7.addWidget(self.n3)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.yess.clicked.connect(lambda: self.yescon(Form))
        self.closee.clicked.connect(lambda: self.nocon(Form))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.old.setText(_translate("Form", "原  密  码："))
        self.numberr.setText(_translate("Form", "账        户："))
        self.yess.setText(_translate("Form", "修        改"))
        self.closee.setText(_translate("Form", "取        消"))
        self.neww.setText(_translate("Form", "新  密  码："))

    def nocon(self, Form):
        Form.close()

    def yescon(self, Form2):
        if len(self.n1.text()) == 0 or len(self.n2.text()) == 0:
            QMessageBox.critical(
                None, "修改失败", "请输入账号密码！", QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
        else:
            f = "SELECT passwd FROM `users` WHERE id = '" + self.n1.text() + "'"
            c = s.con()
            c.execute(f)
            values = c.fetchall()
            if values:
                if len(self.n3.text()) == 0:
                    QMessageBox.critical(
                        None, "修改失败", "修改后密码不能为空！", QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
                else:
                    if str(values[0][0]) == self.n2.text():
                        sql = "UPDATE users SET passwd='%s' WHERE id='%s'" % (
                            self.n3.text(), self.n1.text())
                        c.execute(sql)
                        QMessageBox.information(
                            None, "修改成功", "密码修改成功！", QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
                    else:
                        QMessageBox.critical(
                            None, "修改失败", "原密码错误！", QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
            else:
                QMessageBox.critical(
                    None, "修改失败", "账户不存在！", QMessageBox.Yes | QMessageBox.No, QMessageBox.No)


def showout():
    form = QtWidgets.QDialog()
    ui = Ui_Form()
    ui.setupUi(form)
    form.setWindowTitle("修改密码")
    form.setWindowIcon(QIcon("./data/icon.png"))
    form.show()
    form.exec_()
