# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\QT_program\battry_system\form2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore
from PyQt5 import QtWidgets
from PyQt5.QtGui import QIcon
import SQLb as s
from PyQt5.QtWidgets import QMessageBox


class Ui_Form2(object):
    def setupUi(self, Form2):
        Form2.setObjectName("Form2")
        Form2.resize(469, 380)
        Form2.setStyleSheet("background-color: rgb(225, 237, 255);")
        Form2.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.first = QtWidgets.QWidget(Form2)
        self.first.setGeometry(QtCore.QRect(10, 100, 451, 81))
        self.first.setObjectName("first")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.first)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.number = QtWidgets.QLabel(self.first)
        self.number.setStyleSheet("font:15px \"微软雅黑\";")
        self.number.setObjectName("number")
        self.horizontalLayout_5.addWidget(self.number)
        self.n1 = QtWidgets.QLineEdit(self.first)
        self.n1.setMinimumSize(QtCore.QSize(0, 30))
        self.n1.setStyleSheet("background:white;\n"
                              "    padding-left:5px ;\n"
                              "    padding-top:1px ;\n"
                              "    border-bottom-left-radius:3px;\n"
                              "    border-bottom-right-radius:3px;\n"
                              "    border: 1px solid rgb(209 , 209 , 209);\n"
                              "    border-top:transparent;")
        self.n1.setObjectName("n1")
        self.horizontalLayout_5.addWidget(self.n1)
        self.button = QtWidgets.QWidget(Form2)
        self.button.setGeometry(QtCore.QRect(10, 280, 451, 91))
        self.button.setObjectName("button")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.button)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.yes = QtWidgets.QPushButton(self.button)
        self.yes.setMinimumSize(QtCore.QSize(150, 50))
        self.yes.setStyleSheet("QPushButton\n"
                               "{\n"
                               "    color:white;\n"
                               "    background-color:rgb(14 , 150 , 254);\n"
                               "    border-radius:5px;\n"
                               "    font:20px \"微软雅黑\";\n"
                               "}\n"
                               "\n"
                               "::hover\n"
                               "{\n"
                               "    color:white;\n"
                               "    background-color:rgb(44 , 137 , 255);\n"
                               "}\n"
                               "\n"
                               "::pressed\n"
                               "{\n"
                               "    color:white;\n"
                               "    background-color:rgb(14 , 135 , 228);\n"
                               "    padding-left:3px;\n"
                               "    padding-top:3px;\n"
                               "}")
        self.yes.setObjectName("yes")
        self.horizontalLayout_6.addWidget(self.yes)
        spacerItem = QtWidgets.QSpacerItem(
            82, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.close = QtWidgets.QPushButton(self.button)
        self.close.setMinimumSize(QtCore.QSize(150, 50))
        self.close.setStyleSheet("QPushButton\n"
                                 "{\n"
                                 "    color:white;\n"
                                 "    background-color:rgb(14 , 150 , 254);\n"
                                 "    border-radius:5px;\n"
                                 "    font:20px \"微软雅黑\";\n"
                                 "}\n"
                                 "\n"
                                 ":hover\n"
                                 "{\n"
                                 "    color:white;\n"
                                 "    background-color:rgb(44 , 137 , 255);\n"
                                 "}\n"
                                 "\n"
                                 ":pressed\n"
                                 "{\n"
                                 "    color:white;\n"
                                 "    background-color:rgb(14 , 135 , 228);\n"
                                 "    padding-left:3px;\n"
                                 "    padding-top:3px;\n"
                                 "}")
        self.close.setObjectName("close")
        self.horizontalLayout_6.addWidget(self.close)
        self.second_2 = QtWidgets.QWidget(Form2)
        self.second_2.setGeometry(QtCore.QRect(10, 190, 451, 81))
        self.second_2.setObjectName("second_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.second_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.secret = QtWidgets.QLabel(self.second_2)
        self.secret.setStyleSheet("font:15px \"微软雅黑\";\n"
                                  "background-color: rgb(231, 235, 255);")
        self.secret.setObjectName("secret")
        self.horizontalLayout_7.addWidget(self.secret)
        self.n2 = QtWidgets.QLineEdit(self.second_2)
        self.n2.setMinimumSize(QtCore.QSize(0, 30))
        self.n2.setToolTip("")
        self.n2.setStyleSheet("background:white;\n"
                              "    padding-left:5px ;\n"
                              "    padding-top:1px ;\n"
                              "    border-bottom-left-radius:3px;\n"
                              "    border-bottom-right-radius:3px;\n"
                              "    border: 1px solid rgb(209 , 209 , 209);\n"
                              "    border-top:transparent;")
        self.n2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.n2.setObjectName("n2")
        self.horizontalLayout_7.addWidget(self.n2)
        self.label = QtWidgets.QLabel(Form2)
        self.label.setGeometry(QtCore.QRect(10, 10, 451, 81))
        self.label.setStyleSheet("color: rgb(0, 98, 255);\n"
                                 "background-color: rgb(225, 237, 255);\n"
                                 "font: 17pt \"华文隶书\";")
        self.label.setObjectName("label")
        self.retranslateUi(Form2)
        QtCore.QMetaObject.connectSlotsByName(Form2)
        self.yes.clicked.connect(lambda: self.yescon(Form2))
        self.close.clicked.connect(lambda: self.nocon(Form2))

    def retranslateUi(self, Form2):
        _translate = QtCore.QCoreApplication.translate
        Form2.setWindowTitle(_translate("Form2", "Form"))
        self.number.setText(_translate("Form2", "账        户："))
        self.yes.setText(_translate("Form2", "注        册"))
        self.close.setText(_translate("Form2", "取        消"))
        self.secret.setText(_translate("Form2", "密        码："))
        self.label.setText(_translate("Form2", "  欢迎使用电池盖帽生产线检测系统"))

    def nocon(self, Form2):
        Form2.close()

    def yescon(self, Form2):
        if len(self.n1.text()) == 0 or len(self.n2.text()) == 0:
            QMessageBox.critical(
                None, "创建失败", "请输入账号密码！", QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
        else:
            f = "SELECT passwd FROM `users` WHERE id = '" + self.n1.text() + "'"
            c = s.con()
            c.execute(f)
            values = c.fetchall()
            if values:
                QMessageBox.critical(
                    None, "创建失败", "账号已存在！", QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
            else:
                val = "'" + self.n1.text() + "', '" + self.n2.text() + "', 'user'"
                ins = """INSERT INTO `users`(
                    id,
                    passwd,
                    kind
                ) VALUE(""" + val + ")"""
                c.execute(ins)
                QMessageBox.information(
                    None, "创建成功", "账号创建成功！", QMessageBox.Yes | QMessageBox.No, QMessageBox.No)


def showout():
    form = QtWidgets.QDialog()
    ui = Ui_Form2()
    ui.setupUi(form)
    form.setWindowTitle("注册账户")
    form.setWindowIcon(QIcon("./data/icon.png"))
    form.show()
    form.exec_()
